build:
    environment:
        php:
            version: 7.1
    dependencies:
        before:
            - sudo composer self-update && composer --version
    tests:
        override:
            - phpunit
imports:
    - php

checks:
    php:
        code_rating: true
        duplication: true

tools:
    php_sim: false
    php_cpd: false
    php_pdepend: true
    php_analyzer: true
    php_changetracking: true
    external_code_coverage:
        timeout: 2100 # Timeout in seconds.

filter:
    excluded_paths:
        - tests/*
        - vendor/*
